version: "3"

services:
  db:
    container_name: devaider_mariadb
    image: mysql:8
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always

    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PWD}
    expose:
      - 3306
      - 33060
    ports:
      - "3306:3306"
      - "33060:33060"

  # adminer - bring up only as needed - bypasses nginx
  adminer:
    # default port 8080
    image: adminer:4
    container_name: devaider_adminer
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "9000:8080"

  redis:
    container_name: devaider_redis
    image: redis:7.2.5-alpine
    restart: always
    ports:
      - "${REDIS_PORT}:6379"

  plantuml-server:
    image: plantuml/plantuml-server:jetty
    ports:
      - "9010:8080"
    restart: always
    container_name: devaider_plantuml

  jupyter-lab:
    image: jupyter/datascience-notebook
    ports:
      - "9020:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
    restart: always
    container_name: devaider_jupyter_lab

  nginx:
    # default ports 80, 443 - expose mapping as needed to host
    image: nginx:1.13-alpine
    container_name: devaider_nginx
    restart: unless-stopped

    ports:
      - "9080:80"    # http
      - "9081:443"   # https
    volumes:
      - ../frontend:/var/www/html/web
      - ${NGINX_CONF}:/etc/nginx/conf.d/default.conf
      - ${NGINX_SSL_CERTS}:/etc/ssl:ro
      - ${NGINX_LOGS}:/var/log/nginx
    depends_on:
      - web
  web:
    container_name: devaider
    build: ../backend
    ports:
      - "9090:8080"
    environment:
      - TZ=Asia/Shanghai
    depends_on:
      - db
      - redis

volumes:
  db-data:
      driver: local


