version: "3"

services:
  db:
    container_name: devaider_mariadb
    image: mariadb:latest
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always

    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PWD}
    expose:
      - 3306
      - 33060
    ports:
      - "${DB_PORT}:3306"
      - "33060:33060"

  # adminer - bring up only as needed - bypasses nginx
  adminer:
    # default port 8080
    image: adminer:4
    container_name: devaider_adminer
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "${ADMINER_PORT}:8080"

  redis:
    container_name: devaider_redis
    image: redis:7.2.5-alpine
    command:
      - redis-server
      - --requirepass ${REDIS_PWD} # 设置密码
      - --save 900 1               # 每 15 分钟保存一次快照
      - --save 300 10              # 每 5 分钟至少有 10 次更改时保存快照
      - --save 60 10000            # 每 1 分钟至少有 10000 次更改时保存快照
      - --appendonly yes           # 启用 AOF（追加日志）
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data           # 挂载持久化数据目录
    restart: unless-stopped

  plantuml:
    image: plantuml/plantuml-server:jetty
    ports:
      - "${PLANT_UML_PORT}:8080"
    restart: always
    container_name: devaider_plantuml

  jupyter:
    container_name: devaider_jupyter
    image: jupyter/datascience-notebook
    ports:
      - "${JUPYTER_LAB_PORT}:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - LLM_API_KEY=${DS_LLM_API_KEY}
      - LLM_BASE_URL=${DS_LLM_BASE_URL}
      - LLM_MODEL=${DS_LLM_MODEL}
    volumes:
      - ../doc:/home/jovyan/work
      - ./data:/data  
    restart: always


  nginx:
    # default ports 80, 443 - expose mapping as needed to host
    image: nginx:1.13-alpine
    container_name: devaider_nginx
    restart: unless-stopped

    ports:
      - "${NGINX_HTTP_PORT}:80"    # http
      - "${NGINX_HTTPS_PORT}:443"   # https
    volumes:
      - ../frontend:/var/www/html/web
      - ${NGINX_CONF}:/etc/nginx/conf.d/default.conf
      - ${NGINX_SSL_CERTS}:/etc/certs:ro
      - ${NGINX_LOGS}:/var/log/nginx
    depends_on:
      - web
  web:
    container_name: devaider
    build: ../backend
    ports:
      - "${WEB_PORT}:8080"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./.env:/usr/src/devaider/.env
    depends_on:
      - db
      - redis

volumes:
  db_data:
      driver: local

  redis_data:
      driver: local
