version: "3"

services:
  db:
    container_name: mariadb
    image: mysql:8
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always

    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PWD}
    expose:
      - 3306
      - 33060
    ports:
      - "3306:3306"
      - "33060:33060"

  # adminer - bring up only as needed - bypasses nginx
  adminer:
    # default port 8080
    image: adminer:4
    container_name: adminer
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "9000:8080"

  redis:
    container_name: redis
    image: redis:7.2.5-alpine
    restart: always
    ports:
      - "${REDIS_PORT}:6379"

  plantuml-server:
    image: plantuml/plantuml-server:jetty
    ports:
      - "9010:8080"
    restart: always
    container_name: plantuml_server

  jupyter-lab:
    image: jupyter/datascience-notebook
    ports:
      - "9020:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
    restart: always
    container_name: jupyter_lab

  nginx-static:
    image: nginx
    ports:
      - "9000:80"
    volumes:
      -./html:/usr/share/nginx/html
    restart: always
    container_name: nginx_static

volumes:
  db-data:
      driver: local


